#importing random module for number generation 
import random

s = "Stone"
p = "Paper"
c = "Scissors"

#Warning
Caution = input("You have to choose your input from Stone, Paper or Scissors only. If you make a spelling mistake or you select some other character, then game will always result in a tie so be carefull with your choice. After selecting your input game will tell you what were the inputs given by you and the computer. If everything is fine then press enter to start the game ----->>>>")

#Defining function for deciding game win and lose
def gameWin(comp, you):
    if comp == you:
        return None
    elif comp == s:
        if you == c:
            return False
        elif you == p:
            return True

    elif comp == p:
        if you == s:
            return False
        elif you == c:
            return True

    elif comp == c:
        if you == p:
            return False
        elif you == s:
            return True

    elif comp != you:
        return None

#Generates a Random Number Selected by the Computer
randNo = random.randint(1,3)

#Tells about computer's turn
print("Comp turn: Stone, Paper and Scissors?")

#Assigning meaning to random numbers generated by computer
if randNo == 1:
    comp = 'Stone'
elif randNo == 2:
    comp = 'Paper'
elif randNo == 3:
    comp = 'Scissors'

#Tells about player's turn
you = input("Your turn: Stone, Paper and Scissors:\n ")

#Gives output in terms of Stone, Paper and Scissors
if you == 's':
    show = "Stone"

elif you == 'p':
    show = "Paper"

elif you == 'c':
    show = "Scissors"

#Assigning variable for the result of match between you and the user    
a = gameWin(comp, you)

#Tells us about wether the game is a tie, lose or win
if a == None:
    print("The game is a tie")

if a == False:
    print("You Lose")

if a == True:
    print("You Win!")

#printing inputs being entered by the player
print(f"You chose- {show}")

#printing inputs being entered by the computer
print(f"Comp chose- {comp}")
