f1 = input("Enter the name of the fruit 1: ")
f2 = input("Enter the name of the fruit 2: ")
f3 = input("Enter the name of the fruit 3: ")
f4 = input("Enter the name of the fruit 4: ")
f5 = input("Enter the name of the fruit 5: ")
f6 = input("Enter the name of the fruit 6: ")
f7 = input("Enter the name of the fruit 7: ")
myFruitList = (f1,f2,f3,f4,f5,f6,f7)
print(myFruitList)